package com.itextpdf.text.xml.simpleparser;

import com.itextpdf.text.Chunk;
import com.itextpdf.text.Font;
import com.itextpdf.text.Font.FontFamily;
import com.itextpdf.text.html.HtmlTags;
import com.itextpdf.text.pdf.Barcode128;
import com.itextpdf.text.xml.xmp.PdfProperties;
import java.util.HashMap;
import java.util.Map;

public class EntitiesToSymbol {
    private static final Map<String, Character> MAP = new HashMap();

    static {
        MAP.put("169", Character.valueOf('ã'));
        MAP.put("172", Character.valueOf('Ø'));
        MAP.put("174", Character.valueOf('Ò'));
        MAP.put("177", Character.valueOf('±'));
        MAP.put("215", Character.valueOf('´'));
        MAP.put("247", Character.valueOf('¸'));
        MAP.put("8230", Character.valueOf('¼'));
        MAP.put("8242", Character.valueOf('¢'));
        MAP.put("8243", Character.valueOf('²'));
        MAP.put("8260", Character.valueOf('¤'));
        MAP.put("8364", Character.valueOf('ð'));
        MAP.put("8465", Character.valueOf('Á'));
        MAP.put("8472", Character.valueOf(Barcode128.DEL));
        MAP.put("8476", Character.valueOf('Â'));
        MAP.put("8482", Character.valueOf('Ô'));
        MAP.put("8501", Character.valueOf('À'));
        MAP.put("8592", Character.valueOf('¬'));
        MAP.put("8593", Character.valueOf('­'));
        MAP.put("8594", Character.valueOf('®'));
        MAP.put("8595", Character.valueOf('¯'));
        MAP.put("8596", Character.valueOf('«'));
        MAP.put("8629", Character.valueOf('¿'));
        MAP.put("8656", Character.valueOf('Ü'));
        MAP.put("8657", Character.valueOf('Ý'));
        MAP.put("8658", Character.valueOf('Þ'));
        MAP.put("8659", Character.valueOf('ß'));
        MAP.put("8660", Character.valueOf('Û'));
        MAP.put("8704", Character.valueOf('\"'));
        MAP.put("8706", Character.valueOf('¶'));
        MAP.put("8707", Character.valueOf('$'));
        MAP.put("8709", Character.valueOf(Barcode128.SHIFT));
        MAP.put("8711", Character.valueOf('Ñ'));
        MAP.put("8712", Character.valueOf('Î'));
        MAP.put("8713", Character.valueOf('Ï'));
        MAP.put("8717", Character.valueOf('\''));
        MAP.put("8719", Character.valueOf('Õ'));
        MAP.put("8721", Character.valueOf('å'));
        MAP.put("8722", Character.valueOf('-'));
        MAP.put("8727", Character.valueOf('*'));
        MAP.put("8729", Character.valueOf('·'));
        MAP.put("8730", Character.valueOf('Ö'));
        MAP.put("8733", Character.valueOf('µ'));
        MAP.put("8734", Character.valueOf('¥'));
        MAP.put("8736", Character.valueOf('Ð'));
        MAP.put("8743", Character.valueOf('Ù'));
        MAP.put("8744", Character.valueOf('Ú'));
        MAP.put("8745", Character.valueOf(Barcode128.CODE_C));
        MAP.put("8746", Character.valueOf('È'));
        MAP.put("8747", Character.valueOf('ò'));
        MAP.put("8756", Character.valueOf('\\'));
        MAP.put("8764", Character.valueOf('~'));
        MAP.put("8773", Character.valueOf('@'));
        MAP.put("8776", Character.valueOf('»'));
        MAP.put("8800", Character.valueOf('¹'));
        MAP.put("8801", Character.valueOf('º'));
        MAP.put("8804", Character.valueOf('£'));
        MAP.put("8805", Character.valueOf('³'));
        MAP.put("8834", Character.valueOf(Barcode128.STARTB));
        MAP.put("8835", Character.valueOf('É'));
        MAP.put("8836", Character.valueOf(Barcode128.STARTA));
        MAP.put("8838", Character.valueOf(Barcode128.STARTC));
        MAP.put("8839", Character.valueOf(Barcode128.FNC1));
        MAP.put("8853", Character.valueOf(Barcode128.FNC2));
        MAP.put("8855", Character.valueOf(Barcode128.FNC3));
        MAP.put("8869", Character.valueOf('^'));
        MAP.put("8901", Character.valueOf('×'));
        MAP.put("8992", Character.valueOf('ó'));
        MAP.put("8993", Character.valueOf('õ'));
        MAP.put("9001", Character.valueOf('á'));
        MAP.put("9002", Character.valueOf('ñ'));
        MAP.put("913", Character.valueOf('A'));
        MAP.put("914", Character.valueOf('B'));
        MAP.put("915", Character.valueOf('G'));
        MAP.put("916", Character.valueOf('D'));
        MAP.put("917", Character.valueOf('E'));
        MAP.put("918", Character.valueOf('Z'));
        MAP.put("919", Character.valueOf('H'));
        MAP.put("920", Character.valueOf('Q'));
        MAP.put("921", Character.valueOf('I'));
        MAP.put("922", Character.valueOf('K'));
        MAP.put("923", Character.valueOf('L'));
        MAP.put("924", Character.valueOf('M'));
        MAP.put("925", Character.valueOf('N'));
        MAP.put("926", Character.valueOf('X'));
        MAP.put("927", Character.valueOf('O'));
        MAP.put("928", Character.valueOf('P'));
        MAP.put("929", Character.valueOf('R'));
        MAP.put("931", Character.valueOf('S'));
        MAP.put("932", Character.valueOf('T'));
        MAP.put("933", Character.valueOf('U'));
        MAP.put("934", Character.valueOf('F'));
        MAP.put("935", Character.valueOf('C'));
        MAP.put("936", Character.valueOf('Y'));
        MAP.put("937", Character.valueOf('W'));
        MAP.put("945", Character.valueOf('a'));
        MAP.put("946", Character.valueOf('b'));
        MAP.put("947", Character.valueOf(Barcode128.START_A));
        MAP.put("948", Character.valueOf(Barcode128.CODE_AC_TO_B));
        MAP.put("949", Character.valueOf(Barcode128.CODE_BC_TO_A));
        MAP.put("950", Character.valueOf('z'));
        MAP.put("951", Character.valueOf(Barcode128.START_B));
        MAP.put("952", Character.valueOf('q'));
        MAP.put("953", Character.valueOf(Barcode128.START_C));
        MAP.put("954", Character.valueOf('k'));
        MAP.put("955", Character.valueOf('l'));
        MAP.put("956", Character.valueOf('m'));
        MAP.put("957", Character.valueOf('n'));
        MAP.put("958", Character.valueOf('x'));
        MAP.put("959", Character.valueOf('o'));
        MAP.put("960", Character.valueOf('p'));
        MAP.put("961", Character.valueOf('r'));
        MAP.put("962", Character.valueOf('V'));
        MAP.put("963", Character.valueOf('s'));
        MAP.put("964", Character.valueOf('t'));
        MAP.put("965", Character.valueOf('u'));
        MAP.put("966", Character.valueOf(Barcode128.FNC1_INDEX));
        MAP.put("967", Character.valueOf(Barcode128.CODE_AB_TO_C));
        MAP.put("9674", Character.valueOf('à'));
        MAP.put("968", Character.valueOf('y'));
        MAP.put("969", Character.valueOf('w'));
        MAP.put("977", Character.valueOf('J'));
        MAP.put("978", Character.valueOf('¡'));
        MAP.put("981", Character.valueOf('j'));
        MAP.put("982", Character.valueOf('v'));
        MAP.put("9824", Character.valueOf('ª'));
        MAP.put("9827", Character.valueOf('§'));
        MAP.put("9829", Character.valueOf('©'));
        MAP.put("9830", Character.valueOf('¨'));
        MAP.put("Alpha", Character.valueOf('A'));
        MAP.put("Beta", Character.valueOf('B'));
        MAP.put("Chi", Character.valueOf('C'));
        MAP.put("Delta", Character.valueOf('D'));
        MAP.put("Epsilon", Character.valueOf('E'));
        MAP.put("Eta", Character.valueOf('H'));
        MAP.put("Gamma", Character.valueOf('G'));
        MAP.put("Iota", Character.valueOf('I'));
        MAP.put("Kappa", Character.valueOf('K'));
        MAP.put("Lambda", Character.valueOf('L'));
        MAP.put("Mu", Character.valueOf('M'));
        MAP.put("Nu", Character.valueOf('N'));
        MAP.put("Omega", Character.valueOf('W'));
        MAP.put("Omicron", Character.valueOf('O'));
        MAP.put("Phi", Character.valueOf('F'));
        MAP.put("Pi", Character.valueOf('P'));
        MAP.put("Prime", Character.valueOf('²'));
        MAP.put("Psi", Character.valueOf('Y'));
        MAP.put("Rho", Character.valueOf('R'));
        MAP.put("Sigma", Character.valueOf('S'));
        MAP.put("Tau", Character.valueOf('T'));
        MAP.put("Theta", Character.valueOf('Q'));
        MAP.put("Upsilon", Character.valueOf('U'));
        MAP.put("Xi", Character.valueOf('X'));
        MAP.put("Zeta", Character.valueOf('Z'));
        MAP.put("alefsym", Character.valueOf('À'));
        MAP.put("alpha", Character.valueOf('a'));
        MAP.put("and", Character.valueOf('Ù'));
        MAP.put("ang", Character.valueOf('Ð'));
        MAP.put("asymp", Character.valueOf('»'));
        MAP.put("beta", Character.valueOf('b'));
        MAP.put("cap", Character.valueOf(Barcode128.CODE_C));
        MAP.put("chi", Character.valueOf(Barcode128.CODE_AB_TO_C));
        MAP.put("clubs", Character.valueOf('§'));
        MAP.put("cong", Character.valueOf('@'));
        MAP.put("copy", Character.valueOf('Ó'));
        MAP.put("crarr", Character.valueOf('¿'));
        MAP.put("cup", Character.valueOf('È'));
        MAP.put("dArr", Character.valueOf('ß'));
        MAP.put("darr", Character.valueOf('¯'));
        MAP.put("delta", Character.valueOf(Barcode128.CODE_AC_TO_B));
        MAP.put("diams", Character.valueOf('¨'));
        MAP.put("divide", Character.valueOf('¸'));
        MAP.put("empty", Character.valueOf(Barcode128.SHIFT));
        MAP.put("epsilon", Character.valueOf(Barcode128.CODE_BC_TO_A));
        MAP.put("equiv", Character.valueOf('º'));
        MAP.put("eta", Character.valueOf(Barcode128.START_B));
        MAP.put("euro", Character.valueOf('ð'));
        MAP.put("exist", Character.valueOf('$'));
        MAP.put("forall", Character.valueOf('\"'));
        MAP.put("frasl", Character.valueOf('¤'));
        MAP.put("gamma", Character.valueOf(Barcode128.START_A));
        MAP.put("ge", Character.valueOf('³'));
        MAP.put("hArr", Character.valueOf('Û'));
        MAP.put("harr", Character.valueOf('«'));
        MAP.put("hearts", Character.valueOf('©'));
        MAP.put("hellip", Character.valueOf('¼'));
        MAP.put("horizontal arrow extender", Character.valueOf('¾'));
        MAP.put("image", Character.valueOf('Á'));
        MAP.put("infin", Character.valueOf('¥'));
        MAP.put("int", Character.valueOf('ò'));
        MAP.put("iota", Character.valueOf(Barcode128.START_C));
        MAP.put("isin", Character.valueOf('Î'));
        MAP.put("kappa", Character.valueOf('k'));
        MAP.put("lArr", Character.valueOf('Ü'));
        MAP.put("lambda", Character.valueOf('l'));
        MAP.put("lang", Character.valueOf('á'));
        MAP.put("large brace extender", Character.valueOf('ï'));
        MAP.put("large integral extender", Character.valueOf('ô'));
        MAP.put("large left brace (bottom)", Character.valueOf('î'));
        MAP.put("large left brace (middle)", Character.valueOf('í'));
        MAP.put("large left brace (top)", Character.valueOf('ì'));
        MAP.put("large left bracket (bottom)", Character.valueOf('ë'));
        MAP.put("large left bracket (extender)", Character.valueOf('ê'));
        MAP.put("large left bracket (top)", Character.valueOf('é'));
        MAP.put("large left parenthesis (bottom)", Character.valueOf('è'));
        MAP.put("large left parenthesis (extender)", Character.valueOf('ç'));
        MAP.put("large left parenthesis (top)", Character.valueOf('æ'));
        MAP.put("large right brace (bottom)", Character.valueOf('þ'));
        MAP.put("large right brace (middle)", Character.valueOf('ý'));
        MAP.put("large right brace (top)", Character.valueOf('ü'));
        MAP.put("large right bracket (bottom)", Character.valueOf('û'));
        MAP.put("large right bracket (extender)", Character.valueOf('ú'));
        MAP.put("large right bracket (top)", Character.valueOf('ù'));
        MAP.put("large right parenthesis (bottom)", Character.valueOf('ø'));
        MAP.put("large right parenthesis (extender)", Character.valueOf('÷'));
        MAP.put("large right parenthesis (top)", Character.valueOf('ö'));
        MAP.put("larr", Character.valueOf('¬'));
        MAP.put("le", Character.valueOf('£'));
        MAP.put("lowast", Character.valueOf('*'));
        MAP.put("loz", Character.valueOf('à'));
        MAP.put("minus", Character.valueOf('-'));
        MAP.put("mu", Character.valueOf('m'));
        MAP.put("nabla", Character.valueOf('Ñ'));
        MAP.put("ne", Character.valueOf('¹'));
        MAP.put("not", Character.valueOf('Ø'));
        MAP.put("notin", Character.valueOf('Ï'));
        MAP.put("nsub", Character.valueOf(Barcode128.STARTA));
        MAP.put("nu", Character.valueOf('n'));
        MAP.put("omega", Character.valueOf('w'));
        MAP.put("omicron", Character.valueOf('o'));
        MAP.put("oplus", Character.valueOf(Barcode128.FNC2));
        MAP.put("or", Character.valueOf('Ú'));
        MAP.put("otimes", Character.valueOf(Barcode128.FNC3));
        MAP.put(PdfProperties.PART, Character.valueOf('¶'));
        MAP.put("perp", Character.valueOf('^'));
        MAP.put("phi", Character.valueOf(Barcode128.FNC1_INDEX));
        MAP.put("pi", Character.valueOf('p'));
        MAP.put("piv", Character.valueOf('v'));
        MAP.put("plusmn", Character.valueOf('±'));
        MAP.put("prime", Character.valueOf('¢'));
        MAP.put("prod", Character.valueOf('Õ'));
        MAP.put("prop", Character.valueOf('µ'));
        MAP.put("psi", Character.valueOf('y'));
        MAP.put("rArr", Character.valueOf('Þ'));
        MAP.put("radic", Character.valueOf('Ö'));
        MAP.put("radical extender", Character.valueOf('`'));
        MAP.put("rang", Character.valueOf('ñ'));
        MAP.put("rarr", Character.valueOf('®'));
        MAP.put("real", Character.valueOf('Â'));
        MAP.put("reg", Character.valueOf('Ò'));
        MAP.put("rho", Character.valueOf('r'));
        MAP.put("sdot", Character.valueOf('×'));
        MAP.put("sigma", Character.valueOf('s'));
        MAP.put("sigmaf", Character.valueOf('V'));
        MAP.put("sim", Character.valueOf('~'));
        MAP.put("spades", Character.valueOf('ª'));
        MAP.put(HtmlTags.SUB, Character.valueOf(Barcode128.STARTB));
        MAP.put("sube", Character.valueOf(Barcode128.STARTC));
        MAP.put("sum", Character.valueOf('å'));
        MAP.put(HtmlTags.SUP, Character.valueOf('É'));
        MAP.put("supe", Character.valueOf(Barcode128.FNC1));
        MAP.put("tau", Character.valueOf('t'));
        MAP.put("there4", Character.valueOf('\\'));
        MAP.put("theta", Character.valueOf('q'));
        MAP.put("thetasym", Character.valueOf('J'));
        MAP.put("times", Character.valueOf('´'));
        MAP.put("trade", Character.valueOf('Ô'));
        MAP.put("uArr", Character.valueOf('Ý'));
        MAP.put("uarr", Character.valueOf('­'));
        MAP.put("upsih", Character.valueOf('¡'));
        MAP.put("upsilon", Character.valueOf('u'));
        MAP.put("vertical arrow extender", Character.valueOf('½'));
        MAP.put("weierp", Character.valueOf(Barcode128.DEL));
        MAP.put("xi", Character.valueOf('x'));
        MAP.put("zeta", Character.valueOf('z'));
    }

    public static Chunk get(String e, Font font) {
        char s = getCorrespondingSymbol(e);
        if (s == '\u0000') {
            try {
                return new Chunk(String.valueOf((char) Integer.parseInt(e)), font);
            } catch (Exception e2) {
                return new Chunk(e, font);
            }
        }
        return new Chunk(String.valueOf(s), new Font(FontFamily.SYMBOL, font.getSize(), font.getStyle(), font.getColor()));
    }

    public static char getCorrespondingSymbol(String name) {
        Character symbol = (Character) MAP.get(name);
        if (symbol == null) {
            return '\u0000';
        }
        return symbol.charValue();
    }
}
