package org.apache.poi.hssf.record.chart;

import org.apache.poi.hssf.record.RecordInputStream;
import org.apache.poi.hssf.record.StandardRecord;
import org.apache.poi.util.BitField;
import org.apache.poi.util.BitFieldFactory;
import org.apache.poi.util.HexDump;
import org.apache.poi.util.LittleEndianOutput;

public final class TextRecord extends StandardRecord {
    public static final short DATA_LABEL_PLACEMENT_ABOVE = (short) 5;
    public static final short DATA_LABEL_PLACEMENT_AUTO = (short) 9;
    public static final short DATA_LABEL_PLACEMENT_AXIS = (short) 4;
    public static final short DATA_LABEL_PLACEMENT_BELOW = (short) 6;
    public static final short DATA_LABEL_PLACEMENT_CENTER = (short) 3;
    public static final short DATA_LABEL_PLACEMENT_CHART_DEPENDENT = (short) 0;
    public static final short DATA_LABEL_PLACEMENT_INSIDE = (short) 2;
    public static final short DATA_LABEL_PLACEMENT_LEFT = (short) 7;
    public static final short DATA_LABEL_PLACEMENT_OUTSIDE = (short) 1;
    public static final short DATA_LABEL_PLACEMENT_RIGHT = (short) 8;
    public static final short DATA_LABEL_PLACEMENT_USER_MOVED = (short) 10;
    public static final short DISPLAY_MODE_OPAQUE = (short) 2;
    public static final short DISPLAY_MODE_TRANSPARENT = (short) 1;
    public static final byte HORIZONTAL_ALIGNMENT_BOTTOM = (byte) 3;
    public static final byte HORIZONTAL_ALIGNMENT_CENTER = (byte) 2;
    public static final byte HORIZONTAL_ALIGNMENT_JUSTIFY = (byte) 4;
    public static final byte HORIZONTAL_ALIGNMENT_LEFT = (byte) 1;
    public static final short ROTATION_NONE = (short) 0;
    public static final short ROTATION_ROTATED_90_DEGREES = (short) 2;
    public static final short ROTATION_ROTATED_90_DEGREES_CLOCKWISE = (short) 3;
    public static final short ROTATION_TOP_TO_BOTTOM = (short) 1;
    public static final byte VERTICAL_ALIGNMENT_BOTTOM = (byte) 3;
    public static final byte VERTICAL_ALIGNMENT_CENTER = (byte) 2;
    public static final byte VERTICAL_ALIGNMENT_JUSTIFY = (byte) 4;
    public static final byte VERTICAL_ALIGNMENT_TOP = (byte) 1;
    private static final BitField autoBackground = BitFieldFactory.getInstance(128);
    private static final BitField autoColor = BitFieldFactory.getInstance(1);
    private static final BitField autoGeneratedText = BitFieldFactory.getInstance(16);
    private static final BitField autoLabelDeleted = BitFieldFactory.getInstance(64);
    private static final BitField dataLabelPlacement = BitFieldFactory.getInstance(15);
    private static final BitField generated = BitFieldFactory.getInstance(32);
    private static final BitField rotation = BitFieldFactory.getInstance(1792);
    private static final BitField showBubbleSizes = BitFieldFactory.getInstance(8192);
    private static final BitField showCategoryLabelAsPercentage = BitFieldFactory.getInstance(2048);
    private static final BitField showKey = BitFieldFactory.getInstance(2);
    private static final BitField showLabel = BitFieldFactory.getInstance(16384);
    private static final BitField showValue = BitFieldFactory.getInstance(4);
    private static final BitField showValueAsPercentage = BitFieldFactory.getInstance(4096);
    public static final short sid = (short) 4133;
    private static final BitField vertical = BitFieldFactory.getInstance(8);
    private short field_10_indexOfColorValue;
    private short field_11_options2;
    private short field_12_textRotation;
    private byte field_1_horizontalAlignment;
    private byte field_2_verticalAlignment;
    private short field_3_displayMode;
    private int field_4_rgbColor;
    private int field_5_x;
    private int field_6_y;
    private int field_7_width;
    private int field_8_height;
    private short field_9_options1;

    public TextRecord(RecordInputStream in) {
        this.field_1_horizontalAlignment = in.readByte();
        this.field_2_verticalAlignment = in.readByte();
        this.field_3_displayMode = in.readShort();
        this.field_4_rgbColor = in.readInt();
        this.field_5_x = in.readInt();
        this.field_6_y = in.readInt();
        this.field_7_width = in.readInt();
        this.field_8_height = in.readInt();
        this.field_9_options1 = in.readShort();
        this.field_10_indexOfColorValue = in.readShort();
        this.field_11_options2 = in.readShort();
        this.field_12_textRotation = in.readShort();
    }

    public String toString() {
        StringBuffer buffer = new StringBuffer();
        buffer.append("[TEXT]\n");
        buffer.append("    .horizontalAlignment  = ").append("0x").append(HexDump.toHex(getHorizontalAlignment())).append(" (").append(getHorizontalAlignment()).append(" )");
        buffer.append(System.getProperty("line.separator"));
        buffer.append("    .verticalAlignment    = ").append("0x").append(HexDump.toHex(getVerticalAlignment())).append(" (").append(getVerticalAlignment()).append(" )");
        buffer.append(System.getProperty("line.separator"));
        buffer.append("    .displayMode          = ").append("0x").append(HexDump.toHex(getDisplayMode())).append(" (").append(getDisplayMode()).append(" )");
        buffer.append(System.getProperty("line.separator"));
        buffer.append("    .rgbColor             = ").append("0x").append(HexDump.toHex(getRgbColor())).append(" (").append(getRgbColor()).append(" )");
        buffer.append(System.getProperty("line.separator"));
        buffer.append("    .x                    = ").append("0x").append(HexDump.toHex(getX())).append(" (").append(getX()).append(" )");
        buffer.append(System.getProperty("line.separator"));
        buffer.append("    .y                    = ").append("0x").append(HexDump.toHex(getY())).append(" (").append(getY()).append(" )");
        buffer.append(System.getProperty("line.separator"));
        buffer.append("    .width                = ").append("0x").append(HexDump.toHex(getWidth())).append(" (").append(getWidth()).append(" )");
        buffer.append(System.getProperty("line.separator"));
        buffer.append("    .height               = ").append("0x").append(HexDump.toHex(getHeight())).append(" (").append(getHeight()).append(" )");
        buffer.append(System.getProperty("line.separator"));
        buffer.append("    .options1             = ").append("0x").append(HexDump.toHex(getOptions1())).append(" (").append(getOptions1()).append(" )");
        buffer.append(System.getProperty("line.separator"));
        buffer.append("         .autoColor                = ").append(isAutoColor()).append('\n');
        buffer.append("         .showKey                  = ").append(isShowKey()).append('\n');
        buffer.append("         .showValue                = ").append(isShowValue()).append('\n');
        buffer.append("         .vertical                 = ").append(isVertical()).append('\n');
        buffer.append("         .autoGeneratedText        = ").append(isAutoGeneratedText()).append('\n');
        buffer.append("         .generated                = ").append(isGenerated()).append('\n');
        buffer.append("         .autoLabelDeleted         = ").append(isAutoLabelDeleted()).append('\n');
        buffer.append("         .autoBackground           = ").append(isAutoBackground()).append('\n');
        buffer.append("         .rotation                 = ").append(getRotation()).append('\n');
        buffer.append("         .showCategoryLabelAsPercentage     = ").append(isShowCategoryLabelAsPercentage()).append('\n');
        buffer.append("         .showValueAsPercentage     = ").append(isShowValueAsPercentage()).append('\n');
        buffer.append("         .showBubbleSizes          = ").append(isShowBubbleSizes()).append('\n');
        buffer.append("         .showLabel                = ").append(isShowLabel()).append('\n');
        buffer.append("    .indexOfColorValue    = ").append("0x").append(HexDump.toHex(getIndexOfColorValue())).append(" (").append(getIndexOfColorValue()).append(" )");
        buffer.append(System.getProperty("line.separator"));
        buffer.append("    .options2             = ").append("0x").append(HexDump.toHex(getOptions2())).append(" (").append(getOptions2()).append(" )");
        buffer.append(System.getProperty("line.separator"));
        buffer.append("         .dataLabelPlacement       = ").append(getDataLabelPlacement()).append('\n');
        buffer.append("    .textRotation         = ").append("0x").append(HexDump.toHex(getTextRotation())).append(" (").append(getTextRotation()).append(" )");
        buffer.append(System.getProperty("line.separator"));
        buffer.append("[/TEXT]\n");
        return buffer.toString();
    }

    public void serialize(LittleEndianOutput out) {
        out.writeByte(this.field_1_horizontalAlignment);
        out.writeByte(this.field_2_verticalAlignment);
        out.writeShort(this.field_3_displayMode);
        out.writeInt(this.field_4_rgbColor);
        out.writeInt(this.field_5_x);
        out.writeInt(this.field_6_y);
        out.writeInt(this.field_7_width);
        out.writeInt(this.field_8_height);
        out.writeShort(this.field_9_options1);
        out.writeShort(this.field_10_indexOfColorValue);
        out.writeShort(this.field_11_options2);
        out.writeShort(this.field_12_textRotation);
    }

    protected int getDataSize() {
        return 32;
    }

    public short getSid() {
        return sid;
    }

    public Object clone() {
        TextRecord rec = new TextRecord();
        rec.field_1_horizontalAlignment = this.field_1_horizontalAlignment;
        rec.field_2_verticalAlignment = this.field_2_verticalAlignment;
        rec.field_3_displayMode = this.field_3_displayMode;
        rec.field_4_rgbColor = this.field_4_rgbColor;
        rec.field_5_x = this.field_5_x;
        rec.field_6_y = this.field_6_y;
        rec.field_7_width = this.field_7_width;
        rec.field_8_height = this.field_8_height;
        rec.field_9_options1 = this.field_9_options1;
        rec.field_10_indexOfColorValue = this.field_10_indexOfColorValue;
        rec.field_11_options2 = this.field_11_options2;
        rec.field_12_textRotation = this.field_12_textRotation;
        return rec;
    }

    public byte getHorizontalAlignment() {
        return this.field_1_horizontalAlignment;
    }

    public void setHorizontalAlignment(byte field_1_horizontalAlignment) {
        this.field_1_horizontalAlignment = field_1_horizontalAlignment;
    }

    public byte getVerticalAlignment() {
        return this.field_2_verticalAlignment;
    }

    public void setVerticalAlignment(byte field_2_verticalAlignment) {
        this.field_2_verticalAlignment = field_2_verticalAlignment;
    }

    public short getDisplayMode() {
        return this.field_3_displayMode;
    }

    public void setDisplayMode(short field_3_displayMode) {
        this.field_3_displayMode = field_3_displayMode;
    }

    public int getRgbColor() {
        return this.field_4_rgbColor;
    }

    public void setRgbColor(int field_4_rgbColor) {
        this.field_4_rgbColor = field_4_rgbColor;
    }

    public int getX() {
        return this.field_5_x;
    }

    public void setX(int field_5_x) {
        this.field_5_x = field_5_x;
    }

    public int getY() {
        return this.field_6_y;
    }

    public void setY(int field_6_y) {
        this.field_6_y = field_6_y;
    }

    public int getWidth() {
        return this.field_7_width;
    }

    public void setWidth(int field_7_width) {
        this.field_7_width = field_7_width;
    }

    public int getHeight() {
        return this.field_8_height;
    }

    public void setHeight(int field_8_height) {
        this.field_8_height = field_8_height;
    }

    public short getOptions1() {
        return this.field_9_options1;
    }

    public void setOptions1(short field_9_options1) {
        this.field_9_options1 = field_9_options1;
    }

    public short getIndexOfColorValue() {
        return this.field_10_indexOfColorValue;
    }

    public void setIndexOfColorValue(short field_10_indexOfColorValue) {
        this.field_10_indexOfColorValue = field_10_indexOfColorValue;
    }

    public short getOptions2() {
        return this.field_11_options2;
    }

    public void setOptions2(short field_11_options2) {
        this.field_11_options2 = field_11_options2;
    }

    public short getTextRotation() {
        return this.field_12_textRotation;
    }

    public void setTextRotation(short field_12_textRotation) {
        this.field_12_textRotation = field_12_textRotation;
    }

    public void setAutoColor(boolean value) {
        this.field_9_options1 = autoColor.setShortBoolean(this.field_9_options1, value);
    }

    public boolean isAutoColor() {
        return autoColor.isSet(this.field_9_options1);
    }

    public void setShowKey(boolean value) {
        this.field_9_options1 = showKey.setShortBoolean(this.field_9_options1, value);
    }

    public boolean isShowKey() {
        return showKey.isSet(this.field_9_options1);
    }

    public void setShowValue(boolean value) {
        this.field_9_options1 = showValue.setShortBoolean(this.field_9_options1, value);
    }

    public boolean isShowValue() {
        return showValue.isSet(this.field_9_options1);
    }

    public void setVertical(boolean value) {
        this.field_9_options1 = vertical.setShortBoolean(this.field_9_options1, value);
    }

    public boolean isVertical() {
        return vertical.isSet(this.field_9_options1);
    }

    public void setAutoGeneratedText(boolean value) {
        this.field_9_options1 = autoGeneratedText.setShortBoolean(this.field_9_options1, value);
    }

    public boolean isAutoGeneratedText() {
        return autoGeneratedText.isSet(this.field_9_options1);
    }

    public void setGenerated(boolean value) {
        this.field_9_options1 = generated.setShortBoolean(this.field_9_options1, value);
    }

    public boolean isGenerated() {
        return generated.isSet(this.field_9_options1);
    }

    public void setAutoLabelDeleted(boolean value) {
        this.field_9_options1 = autoLabelDeleted.setShortBoolean(this.field_9_options1, value);
    }

    public boolean isAutoLabelDeleted() {
        return autoLabelDeleted.isSet(this.field_9_options1);
    }

    public void setAutoBackground(boolean value) {
        this.field_9_options1 = autoBackground.setShortBoolean(this.field_9_options1, value);
    }

    public boolean isAutoBackground() {
        return autoBackground.isSet(this.field_9_options1);
    }

    public void setRotation(short value) {
        this.field_9_options1 = rotation.setShortValue(this.field_9_options1, value);
    }

    public short getRotation() {
        return rotation.getShortValue(this.field_9_options1);
    }

    public void setShowCategoryLabelAsPercentage(boolean value) {
        this.field_9_options1 = showCategoryLabelAsPercentage.setShortBoolean(this.field_9_options1, value);
    }

    public boolean isShowCategoryLabelAsPercentage() {
        return showCategoryLabelAsPercentage.isSet(this.field_9_options1);
    }

    public void setShowValueAsPercentage(boolean value) {
        this.field_9_options1 = showValueAsPercentage.setShortBoolean(this.field_9_options1, value);
    }

    public boolean isShowValueAsPercentage() {
        return showValueAsPercentage.isSet(this.field_9_options1);
    }

    public void setShowBubbleSizes(boolean value) {
        this.field_9_options1 = showBubbleSizes.setShortBoolean(this.field_9_options1, value);
    }

    public boolean isShowBubbleSizes() {
        return showBubbleSizes.isSet(this.field_9_options1);
    }

    public void setShowLabel(boolean value) {
        this.field_9_options1 = showLabel.setShortBoolean(this.field_9_options1, value);
    }

    public boolean isShowLabel() {
        return showLabel.isSet(this.field_9_options1);
    }

    public void setDataLabelPlacement(short value) {
        this.field_11_options2 = dataLabelPlacement.setShortValue(this.field_11_options2, value);
    }

    public short getDataLabelPlacement() {
        return dataLabelPlacement.getShortValue(this.field_11_options2);
    }
}
