package org.apache.poi.ddf;

import android.support.v7.widget.helper.ItemTouchHelper.Callback;
import com.google.zxing.pdf417.PDF417Common;
import com.itextpdf.text.Element;
import com.itextpdf.text.pdf.codec.TIFFConstants;
import com.itextpdf.text.pdf.codec.wmf.MetaDo;
import java.util.HashMap;
import java.util.Map;
import org.apache.poi.hssf.usermodel.HSSFShapeTypes;
import org.bytedeco.javacpp.avcodec.AVCodecContext;
import org.bytedeco.javacpp.avformat.AVStream;
import org.bytedeco.javacpp.avutil;
import org.bytedeco.javacpp.dc1394;
import org.bytedeco.javacpp.opencv_videoio;

public final class EscherProperties {
    public static final short BLIP__BLIPFILENAME = (short) 261;
    public static final short BLIP__BLIPFLAGS = (short) 262;
    public static final short BLIP__BLIPTODISPLAY = (short) 260;
    public static final short BLIP__BRIGHTNESSSETTING = (short) 265;
    public static final short BLIP__CONTRASTSETTING = (short) 264;
    public static final short BLIP__CROPFROMBOTTOM = (short) 257;
    public static final short BLIP__CROPFROMLEFT = (short) 258;
    public static final short BLIP__CROPFROMRIGHT = (short) 259;
    public static final short BLIP__CROPFROMTOP = (short) 256;
    public static final short BLIP__DOUBLEMOD = (short) 268;
    public static final short BLIP__GAMMA = (short) 266;
    public static final short BLIP__NOHITTESTPICTURE = (short) 316;
    public static final short BLIP__PICTUREACTIVE = (short) 319;
    public static final short BLIP__PICTUREBILEVEL = (short) 318;
    public static final short BLIP__PICTUREFILLMOD = (short) 269;
    public static final short BLIP__PICTUREGRAY = (short) 317;
    public static final short BLIP__PICTUREID = (short) 267;
    public static final short BLIP__PICTURELINE = (short) 270;
    public static final short BLIP__PRINTBLIP = (short) 271;
    public static final short BLIP__PRINTBLIPFILENAME = (short) 272;
    public static final short BLIP__PRINTFLAGS = (short) 273;
    public static final short BLIP__TRANSPARENTCOLOR = (short) 263;
    public static final short CALLOUT__CALLOUTACCENTBAR = (short) 890;
    public static final short CALLOUT__CALLOUTANGLE = (short) 834;
    public static final short CALLOUT__CALLOUTDROPSPECIFIED = (short) 836;
    public static final short CALLOUT__CALLOUTDROPTYPE = (short) 835;
    public static final short CALLOUT__CALLOUTLENGTHSPECIFIED = (short) 837;
    public static final short CALLOUT__CALLOUTMINUSX = (short) 892;
    public static final short CALLOUT__CALLOUTMINUSY = (short) 893;
    public static final short CALLOUT__CALLOUTTEXTBORDER = (short) 891;
    public static final short CALLOUT__CALLOUTTYPE = (short) 832;
    public static final short CALLOUT__DROPAUTO = (short) 894;
    public static final short CALLOUT__ISCALLOUT = (short) 889;
    public static final short CALLOUT__LENGTHSPECIFIED = (short) 895;
    public static final short CALLOUT__XYCALLOUTGAP = (short) 833;
    public static final short FILL__ANGLE = (short) 395;
    public static final short FILL__BACKOPACITY = (short) 388;
    public static final short FILL__BLIPFILENAME = (short) 391;
    public static final short FILL__BLIPFLAGS = (short) 392;
    public static final short FILL__CRMOD = (short) 389;
    public static final short FILL__DZTYPE = (short) 405;
    public static final short FILL__FILLBACKCOLOR = (short) 387;
    public static final short FILL__FILLCOLOR = (short) 385;
    public static final short FILL__FILLED = (short) 443;
    public static final short FILL__FILLOPACITY = (short) 386;
    public static final short FILL__FILLTYPE = (short) 384;
    public static final short FILL__FOCUS = (short) 396;
    public static final short FILL__HEIGHT = (short) 394;
    public static final short FILL__HITTESTFILL = (short) 444;
    public static final short FILL__NOFILLHITTEST = (short) 447;
    public static final short FILL__ORIGINX = (short) 408;
    public static final short FILL__ORIGINY = (short) 409;
    public static final short FILL__PATTERNTEXTURE = (short) 390;
    public static final short FILL__RECTBOTTOM = (short) 404;
    public static final short FILL__RECTLEFT = (short) 401;
    public static final short FILL__RECTRIGHT = (short) 403;
    public static final short FILL__RECTTOP = (short) 402;
    public static final short FILL__SHADECOLORS = (short) 407;
    public static final short FILL__SHADEPRESET = (short) 406;
    public static final short FILL__SHADETYPE = (short) 412;
    public static final short FILL__SHAPE = (short) 445;
    public static final short FILL__SHAPEORIGINX = (short) 410;
    public static final short FILL__SHAPEORIGINY = (short) 411;
    public static final short FILL__TOBOTTOM = (short) 400;
    public static final short FILL__TOLEFT = (short) 397;
    public static final short FILL__TORIGHT = (short) 399;
    public static final short FILL__TOTOP = (short) 398;
    public static final short FILL__USERECT = (short) 446;
    public static final short FILL__WIDTH = (short) 393;
    public static final short GEOMETRY__3DOK = (short) 379;
    public static final short GEOMETRY__ADJUST10VALUE = (short) 336;
    public static final short GEOMETRY__ADJUST2VALUE = (short) 328;
    public static final short GEOMETRY__ADJUST3VALUE = (short) 329;
    public static final short GEOMETRY__ADJUST4VALUE = (short) 330;
    public static final short GEOMETRY__ADJUST5VALUE = (short) 331;
    public static final short GEOMETRY__ADJUST6VALUE = (short) 332;
    public static final short GEOMETRY__ADJUST7VALUE = (short) 333;
    public static final short GEOMETRY__ADJUST8VALUE = (short) 334;
    public static final short GEOMETRY__ADJUST9VALUE = (short) 335;
    public static final short GEOMETRY__ADJUSTVALUE = (short) 327;
    public static final short GEOMETRY__BOTTOM = (short) 323;
    public static final short GEOMETRY__FILLOK = (short) 383;
    public static final short GEOMETRY__FILLSHADESHAPEOK = (short) 382;
    public static final short GEOMETRY__GEOTEXTOK = (short) 381;
    public static final short GEOMETRY__LEFT = (short) 320;
    public static final short GEOMETRY__LINEOK = (short) 380;
    public static final short GEOMETRY__RIGHT = (short) 322;
    public static final short GEOMETRY__SEGMENTINFO = (short) 326;
    public static final short GEOMETRY__SHADOWok = (short) 378;
    public static final short GEOMETRY__SHAPEPATH = (short) 324;
    public static final short GEOMETRY__TOP = (short) 321;
    public static final short GEOMETRY__VERTICES = (short) 325;
    public static final short GEOTEXT__ALIGNMENTONCURVE = (short) 194;
    public static final short GEOTEXT__BOLDFONT = (short) 250;
    public static final short GEOTEXT__CHARBOUNDINGBOX = (short) 246;
    public static final short GEOTEXT__DEFAULTPOINTSIZE = (short) 195;
    public static final short GEOTEXT__FONTFAMILYNAME = (short) 197;
    public static final short GEOTEXT__HASTEXTEFFECT = (short) 241;
    public static final short GEOTEXT__ITALICFONT = (short) 251;
    public static final short GEOTEXT__KERNCHARACTERS = (short) 243;
    public static final short GEOTEXT__NOMEASUREALONGPATH = (short) 249;
    public static final short GEOTEXT__REVERSEROWORDER = (short) 240;
    public static final short GEOTEXT__ROTATECHARACTERS = (short) 242;
    public static final short GEOTEXT__RTFTEXT = (short) 193;
    public static final short GEOTEXT__SCALETEXTONPATH = (short) 247;
    public static final short GEOTEXT__SHADOWFONT = (short) 253;
    public static final short GEOTEXT__SMALLCAPSFONT = (short) 254;
    public static final short GEOTEXT__STRETCHCHARHEIGHT = (short) 248;
    public static final short GEOTEXT__STRETCHTOFITSHAPE = (short) 245;
    public static final short GEOTEXT__STRIKETHROUGHFONT = (short) 255;
    public static final short GEOTEXT__TEXTSPACING = (short) 196;
    public static final short GEOTEXT__TIGHTORTRACK = (short) 244;
    public static final short GEOTEXT__UNDERLINEFONT = (short) 252;
    public static final short GEOTEXT__UNICODE = (short) 192;
    public static final short GROUPSHAPE__1DADJUSTMENT = (short) 957;
    public static final short GROUPSHAPE__BEHINDDOCUMENT = (short) 954;
    public static final short GROUPSHAPE__BORDERBOTTOMCOLOR = (short) 925;
    public static final short GROUPSHAPE__BORDERLEFTCOLOR = (short) 924;
    public static final short GROUPSHAPE__BORDERRIGHTCOLOR = (short) 926;
    public static final short GROUPSHAPE__BORDERTOPCOLOR = (short) 923;
    public static final short GROUPSHAPE__DESCRIPTION = (short) 897;
    public static final short GROUPSHAPE__EDITEDWRAP = (short) 953;
    public static final short GROUPSHAPE__FLAGS = (short) 959;
    public static final short GROUPSHAPE__HIDDEN = (short) 958;
    public static final short GROUPSHAPE__HR_ALIGN = (short) 916;
    public static final short GROUPSHAPE__HR_HEIGHT = (short) 917;
    public static final short GROUPSHAPE__HR_PCT = (short) 915;
    public static final short GROUPSHAPE__HR_WIDTH = (short) 918;
    public static final short GROUPSHAPE__HYPERLINK = (short) 898;
    public static final short GROUPSHAPE__ISBUTTON = (short) 956;
    public static final short GROUPSHAPE__METROBLOB = (short) 937;
    public static final short GROUPSHAPE__ONDBLCLICKNOTIFY = (short) 955;
    public static final short GROUPSHAPE__POSH = (short) 911;
    public static final short GROUPSHAPE__POSRELH = (short) 912;
    public static final short GROUPSHAPE__POSRELV = (short) 914;
    public static final short GROUPSHAPE__POSV = (short) 913;
    public static final short GROUPSHAPE__PRINT = (short) 959;
    public static final short GROUPSHAPE__REGROUPID = (short) 904;
    public static final short GROUPSHAPE__SCRIPT = (short) 910;
    public static final short GROUPSHAPE__SCRIPTEXT = (short) 919;
    public static final short GROUPSHAPE__SCRIPTLANG = (short) 920;
    public static final short GROUPSHAPE__SHAPENAME = (short) 896;
    public static final short GROUPSHAPE__TABLEPROPERTIES = (short) 927;
    public static final short GROUPSHAPE__TABLEROWPROPERTIES = (short) 928;
    public static final short GROUPSHAPE__TOOLTIP = (short) 909;
    public static final short GROUPSHAPE__UNUSED906 = (short) 906;
    public static final short GROUPSHAPE__WEBBOT = (short) 933;
    public static final short GROUPSHAPE__WRAPDISTBOTTOM = (short) 903;
    public static final short GROUPSHAPE__WRAPDISTLEFT = (short) 900;
    public static final short GROUPSHAPE__WRAPDISTRIGHT = (short) 902;
    public static final short GROUPSHAPE__WRAPDISTTOP = (short) 901;
    public static final short GROUPSHAPE__WRAPPOLYGONVERTICES = (short) 899;
    public static final short GROUPSHAPE__ZORDER = (short) 938;
    public static final short LINESTYLE__ANYLINE = (short) 508;
    public static final short LINESTYLE__ARROWHEADSOK = (short) 507;
    public static final short LINESTYLE__BACKCOLOR = (short) 450;
    public static final short LINESTYLE__COLOR = (short) 448;
    public static final short LINESTYLE__CRMOD = (short) 451;
    public static final short LINESTYLE__FILLBLIP = (short) 453;
    public static final short LINESTYLE__FILLBLIPFLAGS = (short) 455;
    public static final short LINESTYLE__FILLBLIPNAME = (short) 454;
    public static final short LINESTYLE__FILLDZTYPE = (short) 458;
    public static final short LINESTYLE__FILLHEIGHT = (short) 457;
    public static final short LINESTYLE__FILLWIDTH = (short) 456;
    public static final short LINESTYLE__HITLINETEST = (short) 509;
    public static final short LINESTYLE__LINEDASHING = (short) 462;
    public static final short LINESTYLE__LINEDASHSTYLE = (short) 463;
    public static final short LINESTYLE__LINEENDARROWHEAD = (short) 465;
    public static final short LINESTYLE__LINEENDARROWLENGTH = (short) 469;
    public static final short LINESTYLE__LINEENDARROWWIDTH = (short) 468;
    public static final short LINESTYLE__LINEENDCAPSTYLE = (short) 471;
    public static final short LINESTYLE__LINEFILLSHAPE = (short) 510;
    public static final short LINESTYLE__LINEJOINSTYLE = (short) 470;
    public static final short LINESTYLE__LINEMITERLIMIT = (short) 460;
    public static final short LINESTYLE__LINESTARTARROWHEAD = (short) 464;
    public static final short LINESTYLE__LINESTARTARROWLENGTH = (short) 467;
    public static final short LINESTYLE__LINESTARTARROWWIDTH = (short) 466;
    public static final short LINESTYLE__LINESTYLE = (short) 461;
    public static final short LINESTYLE__LINETYPE = (short) 452;
    public static final short LINESTYLE__LINEWIDTH = (short) 459;
    public static final short LINESTYLE__NOLINEDRAWDASH = (short) 511;
    public static final short LINESTYLE__NOLINEDRAWDASH_BOTTOM = (short) 1599;
    public static final short LINESTYLE__NOLINEDRAWDASH_LEFT = (short) 1407;
    public static final short LINESTYLE__NOLINEDRAWDASH_RIGHT = (short) 1535;
    public static final short LINESTYLE__NOLINEDRAWDASH_TOP = (short) 1471;
    public static final short LINESTYLE__OPACITY = (short) 449;
    public static final short PERSPECTIVE__OFFSETX = (short) 577;
    public static final short PERSPECTIVE__OFFSETY = (short) 578;
    public static final short PERSPECTIVE__ORIGINX = (short) 586;
    public static final short PERSPECTIVE__ORIGINY = (short) 587;
    public static final short PERSPECTIVE__PERSPECTIVEON = (short) 639;
    public static final short PERSPECTIVE__PERSPECTIVEX = (short) 583;
    public static final short PERSPECTIVE__PERSPECTIVEY = (short) 584;
    public static final short PERSPECTIVE__SCALEXTOX = (short) 579;
    public static final short PERSPECTIVE__SCALEXTOY = (short) 581;
    public static final short PERSPECTIVE__SCALEYTOX = (short) 580;
    public static final short PERSPECTIVE__SCALEYTOY = (short) 582;
    public static final short PERSPECTIVE__TYPE = (short) 576;
    public static final short PERSPECTIVE__WEIGHT = (short) 585;
    public static final short PROTECTION__LOCKADJUSTHANDLES = (short) 126;
    public static final short PROTECTION__LOCKAGAINSTGROUPING = (short) 127;
    public static final short PROTECTION__LOCKAGAINSTSELECT = (short) 122;
    public static final short PROTECTION__LOCKASPECTRATIO = (short) 120;
    public static final short PROTECTION__LOCKCROPPING = (short) 123;
    public static final short PROTECTION__LOCKPOSITION = (short) 121;
    public static final short PROTECTION__LOCKROTATION = (short) 119;
    public static final short PROTECTION__LOCKTEXT = (short) 125;
    public static final short PROTECTION__LOCKVERTICES = (short) 124;
    public static final short SHADOWSTYLE__COLOR = (short) 513;
    public static final short SHADOWSTYLE__CRMOD = (short) 515;
    public static final short SHADOWSTYLE__HIGHLIGHT = (short) 514;
    public static final short SHADOWSTYLE__OFFSETX = (short) 517;
    public static final short SHADOWSTYLE__OFFSETY = (short) 518;
    public static final short SHADOWSTYLE__OPACITY = (short) 516;
    public static final short SHADOWSTYLE__ORIGINX = (short) 528;
    public static final short SHADOWSTYLE__ORIGINY = (short) 529;
    public static final short SHADOWSTYLE__PERSPECTIVEX = (short) 525;
    public static final short SHADOWSTYLE__PERSPECTIVEY = (short) 526;
    public static final short SHADOWSTYLE__SCALEXTOX = (short) 521;
    public static final short SHADOWSTYLE__SCALEXTOY = (short) 523;
    public static final short SHADOWSTYLE__SCALEYTOX = (short) 522;
    public static final short SHADOWSTYLE__SCALEYTOY = (short) 524;
    public static final short SHADOWSTYLE__SECONDOFFSETX = (short) 519;
    public static final short SHADOWSTYLE__SECONDOFFSETY = (short) 520;
    public static final short SHADOWSTYLE__SHADOW = (short) 574;
    public static final short SHADOWSTYLE__SHADOWOBSURED = (short) 575;
    public static final short SHADOWSTYLE__TYPE = (short) 512;
    public static final short SHADOWSTYLE__WEIGHT = (short) 527;
    public static final short SHAPE__BACKGROUNDSHAPE = (short) 831;
    public static final short SHAPE__BLACKANDWHITESETTINGS = (short) 772;
    public static final short SHAPE__CONNECTORSTYLE = (short) 771;
    public static final short SHAPE__DELETEATTACHEDOBJECT = (short) 830;
    public static final short SHAPE__LOCKSHAPETYPE = (short) 828;
    public static final short SHAPE__MASTER = (short) 769;
    public static final short SHAPE__OLEICON = (short) 826;
    public static final short SHAPE__PREFERRELATIVERESIZE = (short) 827;
    public static final short SHAPE__WMODEBW = (short) 774;
    public static final short SHAPE__WMODEPUREBW = (short) 773;
    public static final short TEXT__ANCHORTEXT = (short) 135;
    public static final short TEXT__BIDIR = (short) 139;
    public static final short TEXT__FONTROTATION = (short) 137;
    public static final short TEXT__IDOFNEXTSHAPE = (short) 138;
    public static final short TEXT__ROTATETEXTWITHSHAPE = (short) 189;
    public static final short TEXT__SCALETEXT = (short) 134;
    public static final short TEXT__SINGLECLICKSELECTS = (short) 187;
    public static final short TEXT__SIZESHAPETOFITTEXT = (short) 190;
    public static final short TEXT__SIZE_TEXT_TO_FIT_SHAPE = (short) 191;
    public static final short TEXT__TEXTBOTTOM = (short) 132;
    public static final short TEXT__TEXTFLOW = (short) 136;
    public static final short TEXT__TEXTID = (short) 128;
    public static final short TEXT__TEXTLEFT = (short) 129;
    public static final short TEXT__TEXTRIGHT = (short) 131;
    public static final short TEXT__TEXTTOP = (short) 130;
    public static final short TEXT__USEHOSTMARGINS = (short) 188;
    public static final short TEXT__WRAPTEXT = (short) 133;
    public static final short THREEDSTYLE__AMBIENTINTENSITY = (short) 722;
    public static final short THREEDSTYLE__CONSTRAINROTATION = (short) 763;
    public static final short THREEDSTYLE__FILLHARSH = (short) 767;
    public static final short THREEDSTYLE__FILLINTENSITY = (short) 730;
    public static final short THREEDSTYLE__FILLX = (short) 727;
    public static final short THREEDSTYLE__FILLY = (short) 728;
    public static final short THREEDSTYLE__FILLZ = (short) 729;
    public static final short THREEDSTYLE__KEYHARSH = (short) 766;
    public static final short THREEDSTYLE__KEYINTENSITY = (short) 726;
    public static final short THREEDSTYLE__KEYX = (short) 723;
    public static final short THREEDSTYLE__KEYY = (short) 724;
    public static final short THREEDSTYLE__KEYZ = (short) 725;
    public static final short THREEDSTYLE__ORIGINX = (short) 718;
    public static final short THREEDSTYLE__ORIGINY = (short) 719;
    public static final short THREEDSTYLE__PARALLEL = (short) 765;
    public static final short THREEDSTYLE__RENDERMODE = (short) 713;
    public static final short THREEDSTYLE__ROTATIONANGLE = (short) 709;
    public static final short THREEDSTYLE__ROTATIONAXISX = (short) 706;
    public static final short THREEDSTYLE__ROTATIONAXISY = (short) 707;
    public static final short THREEDSTYLE__ROTATIONAXISZ = (short) 708;
    public static final short THREEDSTYLE__ROTATIONCENTERAUTO = (short) 764;
    public static final short THREEDSTYLE__ROTATIONCENTERX = (short) 710;
    public static final short THREEDSTYLE__ROTATIONCENTERY = (short) 711;
    public static final short THREEDSTYLE__ROTATIONCENTERZ = (short) 712;
    public static final short THREEDSTYLE__SKEWAMOUNT = (short) 721;
    public static final short THREEDSTYLE__SKEWANGLE = (short) 720;
    public static final short THREEDSTYLE__TOLERANCE = (short) 714;
    public static final short THREEDSTYLE__XROTATIONANGLE = (short) 705;
    public static final short THREEDSTYLE__XVIEWPOINT = (short) 715;
    public static final short THREEDSTYLE__YROTATIONANGLE = (short) 704;
    public static final short THREEDSTYLE__YVIEWPOINT = (short) 716;
    public static final short THREEDSTYLE__ZVIEWPOINT = (short) 717;
    public static final short THREED__3DEFFECT = (short) 700;
    public static final short THREED__CRMOD = (short) 648;
    public static final short THREED__DIFFUSEAMOUNT = (short) 661;
    public static final short THREED__EDGETHICKNESS = (short) 663;
    public static final short THREED__EXTRUDEBACKWARD = (short) 665;
    public static final short THREED__EXTRUDEFORWARD = (short) 664;
    public static final short THREED__EXTRUDEPLANE = (short) 666;
    public static final short THREED__EXTRUSIONCOLOR = (short) 667;
    public static final short THREED__LIGHTFACE = (short) 703;
    public static final short THREED__METALLIC = (short) 701;
    public static final short THREED__SHININESS = (short) 662;
    public static final short THREED__SPECULARAMOUNT = (short) 640;
    public static final short THREED__USEEXTRUSIONCOLOR = (short) 702;
    public static final short TRANSFORM__ROTATION = (short) 4;
    private static final Map<Short, EscherPropertyMetaData> properties = initProps();

    private static Map<Short, EscherPropertyMetaData> initProps() {
        Map<Short, EscherPropertyMetaData> m = new HashMap();
        addProp(m, 4, "transform.rotation");
        addProp(m, 119, "protection.lockrotation");
        addProp(m, 120, "protection.lockaspectratio");
        addProp(m, 121, "protection.lockposition");
        addProp(m, 122, "protection.lockagainstselect");
        addProp(m, 123, "protection.lockcropping");
        addProp(m, 124, "protection.lockvertices");
        addProp(m, 125, "protection.locktext");
        addProp(m, 126, "protection.lockadjusthandles");
        addProp(m, 127, "protection.lockagainstgrouping", (byte) 1);
        addProp(m, 128, "text.textid");
        addProp(m, 129, "text.textleft");
        addProp(m, 130, "text.texttop");
        addProp(m, 131, "text.textright");
        addProp(m, 132, "text.textbottom");
        addProp(m, 133, "text.wraptext");
        addProp(m, 134, "text.scaletext");
        addProp(m, 135, "text.anchortext");
        addProp(m, 136, "text.textflow");
        addProp(m, 137, "text.fontrotation");
        addProp(m, 138, "text.idofnextshape");
        addProp(m, 139, "text.bidir");
        addProp(m, 187, "text.singleclickselects");
        addProp(m, 188, "text.usehostmargins");
        addProp(m, 189, "text.rotatetextwithshape");
        addProp(m, 190, "text.sizeshapetofittext");
        addProp(m, 191, "text.sizetexttofitshape", (byte) 1);
        addProp(m, 192, "geotext.unicode");
        addProp(m, HSSFShapeTypes.ActionButtonForwardNext, "geotext.rtftext");
        addProp(m, HSSFShapeTypes.ActionButtonBackPrevious, "geotext.alignmentoncurve");
        addProp(m, HSSFShapeTypes.ActionButtonEnd, "geotext.defaultpointsize");
        addProp(m, HSSFShapeTypes.ActionButtonBeginning, "geotext.textspacing");
        addProp(m, HSSFShapeTypes.ActionButtonReturn, "geotext.fontfamilyname");
        addProp(m, 240, "geotext.reverseroworder");
        addProp(m, 241, "geotext.hastexteffect");
        addProp(m, 242, "geotext.rotatecharacters");
        addProp(m, 243, "geotext.kerncharacters");
        addProp(m, AVCodecContext.FF_PROFILE_H264_HIGH_444_PREDICTIVE, "geotext.tightortrack");
        addProp(m, 245, "geotext.stretchtofitshape");
        addProp(m, 246, "geotext.charboundingbox");
        addProp(m, MetaDo.META_CREATEPALETTE, "geotext.scaletextonpath");
        addProp(m, 248, "geotext.stretchcharheight");
        addProp(m, 249, "geotext.nomeasurealongpath");
        addProp(m, Callback.DEFAULT_SWIPE_ANIMATION_DURATION, "geotext.boldfont");
        addProp(m, 251, "geotext.italicfont");
        addProp(m, 252, "geotext.underlinefont");
        addProp(m, 253, "geotext.shadowfont");
        addProp(m, 254, "geotext.smallcapsfont");
        addProp(m, 255, "geotext.strikethroughfont");
        addProp(m, 256, "blip.cropfromtop");
        addProp(m, 257, "blip.cropfrombottom");
        addProp(m, 258, "blip.cropfromleft");
        addProp(m, 259, "blip.cropfromright");
        addProp(m, MetaDo.META_SETROP2, "blip.bliptodisplay");
        addProp(m, MetaDo.META_SETRELABS, "blip.blipfilename");
        addProp(m, 262, "blip.blipflags");
        addProp(m, 263, "blip.transparentcolor");
        addProp(m, 264, "blip.contrastsetting");
        addProp(m, TIFFConstants.TIFFTAG_CELLLENGTH, "blip.brightnesssetting");
        addProp(m, TIFFConstants.TIFFTAG_FILLORDER, "blip.gamma");
        addProp(m, 267, "blip.pictureid");
        addProp(m, 268, "blip.doublemod");
        addProp(m, TIFFConstants.TIFFTAG_DOCUMENTNAME, "blip.picturefillmod");
        addProp(m, 270, "blip.pictureline");
        addProp(m, 271, "blip.printblip");
        addProp(m, TIFFConstants.TIFFTAG_MODEL, "blip.printblipfilename");
        addProp(m, TIFFConstants.TIFFTAG_STRIPOFFSETS, "blip.printflags");
        addProp(m, 316, "blip.nohittestpicture");
        addProp(m, 317, "blip.picturegray");
        addProp(m, 318, "blip.picturebilevel");
        addProp(m, 319, "blip.pictureactive");
        addProp(m, 320, "geometry.left");
        addProp(m, 321, "geometry.top");
        addProp(m, 322, "geometry.right");
        addProp(m, 323, "geometry.bottom");
        addProp(m, 324, "geometry.shapepath", (byte) 3);
        addProp(m, 325, "geometry.vertices", (byte) 5);
        addProp(m, 326, "geometry.segmentinfo", (byte) 5);
        addProp(m, 327, "geometry.adjustvalue");
        addProp(m, 328, "geometry.adjust2value");
        addProp(m, avutil.AV_PIX_FMT_YUV440P10BE, "geometry.adjust3value");
        addProp(m, 330, "geometry.adjust4value");
        addProp(m, avutil.AV_PIX_FMT_YUV440P12BE, "geometry.adjust5value");
        addProp(m, 332, "geometry.adjust6value");
        addProp(m, 333, "geometry.adjust7value");
        addProp(m, 334, "geometry.adjust8value");
        addProp(m, avutil.AV_PIX_FMT_P010LE, "geometry.adjust9value");
        addProp(m, 336, "geometry.adjust10value");
        addProp(m, 378, "geometry.shadowOK");
        addProp(m, 379, "geometry.3dok");
        addProp(m, 380, "geometry.lineok");
        addProp(m, 381, "geometry.geotextok");
        addProp(m, 382, "geometry.fillshadeshapeok");
        addProp(m, 383, "geometry.fillok", (byte) 1);
        addProp(m, 384, "fill.filltype");
        addProp(m, dc1394.DC1394_TRIGGER_MODE_1, "fill.fillcolor", (byte) 2);
        addProp(m, dc1394.DC1394_TRIGGER_MODE_2, "fill.fillopacity");
        addProp(m, dc1394.DC1394_TRIGGER_MODE_3, "fill.fillbackcolor", (byte) 2);
        addProp(m, dc1394.DC1394_TRIGGER_MODE_4, "fill.backopacity");
        addProp(m, dc1394.DC1394_TRIGGER_MODE_5, "fill.crmod");
        addProp(m, dc1394.DC1394_TRIGGER_MODE_14, "fill.patterntexture");
        addProp(m, 391, "fill.blipfilename");
        addProp(m, 392, "fill.blipflags");
        addProp(m, 393, "fill.width");
        addProp(m, 394, "fill.height");
        addProp(m, 395, "fill.angle");
        addProp(m, 396, "fill.focus");
        addProp(m, 397, "fill.toleft");
        addProp(m, 398, "fill.totop");
        addProp(m, AVStream.MAX_STD_TIMEBASES, "fill.toright");
        addProp(m, 400, "fill.tobottom");
        addProp(m, 401, "fill.rectleft");
        addProp(m, 402, "fill.recttop");
        addProp(m, 403, "fill.rectright");
        addProp(m, 404, "fill.rectbottom");
        addProp(m, 405, "fill.dztype");
        addProp(m, 406, "fill.shadepreset");
        addProp(m, 407, "fill.shadecolors", (byte) 5);
        addProp(m, 408, "fill.originx");
        addProp(m, 409, "fill.originy");
        addProp(m, 410, "fill.shapeoriginx");
        addProp(m, 411, "fill.shapeoriginy");
        addProp(m, 412, "fill.shadetype");
        addProp(m, 443, "fill.filled");
        addProp(m, 444, "fill.hittestfill");
        addProp(m, opencv_videoio.CV_CAP_PROP_XI_BPC, "fill.shape");
        addProp(m, 446, "fill.userect");
        addProp(m, 447, "fill.nofillhittest", (byte) 1);
        addProp(m, opencv_videoio.CV_CAP_PROP_XI_WB_KR, "linestyle.color", (byte) 2);
        addProp(m, opencv_videoio.CV_CAP_PROP_XI_WB_KG, "linestyle.opacity");
        addProp(m, opencv_videoio.CV_CAP_PROP_XI_WB_KB, "linestyle.backcolor", (byte) 2);
        addProp(m, opencv_videoio.CV_CAP_PROP_XI_WIDTH, "linestyle.crmod");
        addProp(m, opencv_videoio.CV_CAP_PROP_XI_HEIGHT, "linestyle.linetype");
        addProp(m, 453, "linestyle.fillblip");
        addProp(m, 454, "linestyle.fillblipname");
        addProp(m, 455, "linestyle.fillblipflags");
        addProp(m, 456, "linestyle.fillwidth");
        addProp(m, 457, "linestyle.fillheight");
        addProp(m, 458, "linestyle.filldztype");
        addProp(m, opencv_videoio.CV_CAP_PROP_XI_LIMIT_BANDWIDTH, "linestyle.linewidth");
        addProp(m, opencv_videoio.CV_CAP_PROP_XI_SENSOR_DATA_BIT_DEPTH, "linestyle.linemiterlimit");
        addProp(m, opencv_videoio.CV_CAP_PROP_XI_OUTPUT_DATA_BIT_DEPTH, "linestyle.linestyle");
        addProp(m, opencv_videoio.CV_CAP_PROP_XI_IMAGE_DATA_BIT_DEPTH, "linestyle.linedashing");
        addProp(m, opencv_videoio.CV_CAP_PROP_XI_OUTPUT_DATA_PACKING, "linestyle.linedashstyle", (byte) 5);
        addProp(m, opencv_videoio.CV_CAP_PROP_XI_OUTPUT_DATA_PACKING_TYPE, "linestyle.linestartarrowhead");
        addProp(m, opencv_videoio.CV_CAP_PROP_XI_IS_COOLED, "linestyle.lineendarrowhead");
        addProp(m, opencv_videoio.CV_CAP_PROP_XI_COOLING, "linestyle.linestartarrowwidth");
        addProp(m, opencv_videoio.CV_CAP_PROP_XI_TARGET_TEMP, "linestyle.linestartarrowlength");
        addProp(m, opencv_videoio.CV_CAP_PROP_XI_CHIP_TEMP, "linestyle.lineendarrowwidth");
        addProp(m, opencv_videoio.CV_CAP_PROP_XI_HOUS_TEMP, "linestyle.lineendarrowlength");
        addProp(m, opencv_videoio.CV_CAP_PROP_XI_CMS, "linestyle.linejoinstyle");
        addProp(m, opencv_videoio.CV_CAP_PROP_XI_APPLY_CMS, "linestyle.lineendcapstyle");
        addProp(m, opencv_videoio.CV_CAP_PROP_XI_DEBOUNCE_EN, "linestyle.arrowheadsok");
        addProp(m, opencv_videoio.CV_CAP_PROP_XI_DEBOUNCE_T0, "linestyle.anyline");
        addProp(m, opencv_videoio.CV_CAP_PROP_XI_DEBOUNCE_T1, "linestyle.hitlinetest");
        addProp(m, opencv_videoio.CV_CAP_PROP_XI_DEBOUNCE_POL, "linestyle.linefillshape");
        addProp(m, 511, "linestyle.nolinedrawdash", (byte) 1);
        addProp(m, 1407, "linestyle.nolinedrawdash.left", (byte) 1);
        addProp(m, 1471, "linestyle.nolinedrawdash.top", (byte) 1);
        addProp(m, avutil.AV_CH_LAYOUT_7POINT1, "linestyle.nolinedrawdash.bottom", (byte) 1);
        addProp(m, 1535, "linestyle.nolinedrawdash.right", (byte) 1);
        addProp(m, 512, "shadowstyle.type");
        addProp(m, 513, "shadowstyle.color", (byte) 2);
        addProp(m, 514, "shadowstyle.highlight");
        addProp(m, 515, "shadowstyle.crmod");
        addProp(m, opencv_videoio.CV_CAP_PROP_XI_LENS_FOCAL_LENGTH, "shadowstyle.opacity");
        addProp(m, 517, "shadowstyle.offsetx");
        addProp(m, 518, "shadowstyle.offsety");
        addProp(m, TIFFConstants.TIFFTAG_JPEGQTABLES, "shadowstyle.secondoffsetx");
        addProp(m, TIFFConstants.TIFFTAG_JPEGDCTABLES, "shadowstyle.secondoffsety");
        addProp(m, 521, "shadowstyle.scalextox");
        addProp(m, 522, "shadowstyle.scaleytox");
        addProp(m, MetaDo.META_SETWINDOWORG, "shadowstyle.scalextoy");
        addProp(m, MetaDo.META_SETWINDOWEXT, "shadowstyle.scaleytoy");
        addProp(m, MetaDo.META_SETVIEWPORTORG, "shadowstyle.perspectivex");
        addProp(m, MetaDo.META_SETVIEWPORTEXT, "shadowstyle.perspectivey");
        addProp(m, MetaDo.META_OFFSETWINDOWORG, "shadowstyle.weight");
        addProp(m, 528, "shadowstyle.originx");
        addProp(m, 529, "shadowstyle.originy");
        addProp(m, 574, "shadowstyle.shadow");
        addProp(m, 575, "shadowstyle.shadowobscured");
        addProp(m, 576, "perspective.type");
        addProp(m, dc1394.DC1394_TRIGGER_SOURCE_1, "perspective.offsetx");
        addProp(m, 578, "perspective.offsety");
        addProp(m, dc1394.DC1394_TRIGGER_SOURCE_3, "perspective.scalextox");
        addProp(m, 580, "perspective.scaleytox");
        addProp(m, opencv_videoio.CV_CAP_PROP_XI_FREE_FFS_SIZE, "perspective.scalextoy");
        addProp(m, opencv_videoio.CV_CAP_PROP_XI_USED_FFS_SIZE, "perspective.scaleytoy");
        addProp(m, opencv_videoio.CV_CAP_PROP_XI_FFS_ACCESS_KEY, "perspective.perspectivex");
        addProp(m, 584, "perspective.perspectivey");
        addProp(m, opencv_videoio.CV_CAP_PROP_XI_SENSOR_FEATURE_SELECTOR, "perspective.weight");
        addProp(m, opencv_videoio.CV_CAP_PROP_XI_SENSOR_FEATURE_VALUE, "perspective.originx");
        addProp(m, 587, "perspective.originy");
        addProp(m, 639, "perspective.perspectiveon");
        addProp(m, 640, "3d.specularamount");
        addProp(m, 661, "3d.diffuseamount");
        addProp(m, 662, "3d.shininess");
        addProp(m, 663, "3d.edgethickness");
        addProp(m, 664, "3d.extrudeforward");
        addProp(m, 665, "3d.extrudebackward");
        addProp(m, Element.WRITABLE_DIRECT, "3d.extrudeplane");
        addProp(m, 667, "3d.extrusioncolor", (byte) 2);
        addProp(m, 648, "3d.crmod");
        addProp(m, 700, "3d.3deffect");
        addProp(m, 701, "3d.metallic");
        addProp(m, 702, "3d.useextrusioncolor", (byte) 2);
        addProp(m, 703, "3d.lightface");
        addProp(m, 704, "3dstyle.yrotationangle");
        addProp(m, 705, "3dstyle.xrotationangle");
        addProp(m, 706, "3dstyle.rotationaxisx");
        addProp(m, 707, "3dstyle.rotationaxisy");
        addProp(m, 708, "3dstyle.rotationaxisz");
        addProp(m, 709, "3dstyle.rotationangle");
        addProp(m, 710, "3dstyle.rotationcenterx");
        addProp(m, 711, "3dstyle.rotationcentery");
        addProp(m, 712, "3dstyle.rotationcenterz");
        addProp(m, 713, "3dstyle.rendermode");
        addProp(m, 714, "3dstyle.tolerance");
        addProp(m, 715, "3dstyle.xviewpoint");
        addProp(m, 716, "3dstyle.yviewpoint");
        addProp(m, 717, "3dstyle.zviewpoint");
        addProp(m, 718, "3dstyle.originx");
        addProp(m, 719, "3dstyle.originy");
        addProp(m, 720, "3dstyle.skewangle");
        addProp(m, 721, "3dstyle.skewamount");
        addProp(m, 722, "3dstyle.ambientintensity");
        addProp(m, 723, "3dstyle.keyx");
        addProp(m, 724, "3dstyle.keyy");
        addProp(m, 725, "3dstyle.keyz");
        addProp(m, 726, "3dstyle.keyintensity");
        addProp(m, 727, "3dstyle.fillx");
        addProp(m, 728, "3dstyle.filly");
        addProp(m, 729, "3dstyle.fillz");
        addProp(m, 730, "3dstyle.fillintensity");
        addProp(m, MetaDo.META_CREATEFONTINDIRECT, "3dstyle.constrainrotation");
        addProp(m, MetaDo.META_CREATEBRUSHINDIRECT, "3dstyle.rotationcenterauto");
        addProp(m, 765, "3dstyle.parallel");
        addProp(m, 766, "3dstyle.keyharsh");
        addProp(m, 767, "3dstyle.fillharsh");
        addProp(m, dc1394.DC1394_LOG_WARNING, "shape.master");
        addProp(m, 771, "shape.connectorstyle");
        addProp(m, 772, "shape.blackandwhitesettings");
        addProp(m, 773, "shape.wmodepurebw");
        addProp(m, 774, "shape.wmodebw");
        addProp(m, 826, "shape.oleicon");
        addProp(m, 827, "shape.preferrelativeresize");
        addProp(m, 828, "shape.lockshapetype");
        addProp(m, 830, "shape.deleteattachedobject");
        addProp(m, 831, "shape.backgroundshape");
        addProp(m, 832, "callout.callouttype");
        addProp(m, 833, "callout.xycalloutgap");
        addProp(m, 834, "callout.calloutangle");
        addProp(m, 835, "callout.calloutdroptype");
        addProp(m, 836, "callout.calloutdropspecified");
        addProp(m, 837, "callout.calloutlengthspecified");
        addProp(m, 889, "callout.iscallout");
        addProp(m, 890, "callout.calloutaccentbar");
        addProp(m, 891, "callout.callouttextborder");
        addProp(m, 892, "callout.calloutminusx");
        addProp(m, 893, "callout.calloutminusy");
        addProp(m, 894, "callout.dropauto");
        addProp(m, 895, "callout.lengthspecified");
        addProp(m, 896, "groupshape.shapename");
        addProp(m, 897, "groupshape.description");
        addProp(m, 898, "groupshape.hyperlink");
        addProp(m, 899, "groupshape.wrappolygonvertices", (byte) 5);
        addProp(m, 900, "groupshape.wrapdistleft");
        addProp(m, 901, "groupshape.wrapdisttop");
        addProp(m, 902, "groupshape.wrapdistright");
        addProp(m, 903, "groupshape.wrapdistbottom");
        addProp(m, 904, "groupshape.regroupid");
        addProp(m, 906, "unused906");
        addProp(m, 909, "groupshape.wzTooltip");
        addProp(m, 910, "groupshape.wzScript");
        addProp(m, 911, "groupshape.posh");
        addProp(m, 912, "groupshape.posrelh");
        addProp(m, 913, "groupshape.posv");
        addProp(m, 914, "groupshape.posrelv");
        addProp(m, 915, "groupshape.pctHR");
        addProp(m, 916, "groupshape.alignHR");
        addProp(m, 917, "groupshape.dxHeightHR");
        addProp(m, 918, "groupshape.dxWidthHR");
        addProp(m, 919, "groupshape.wzScriptExtAttr");
        addProp(m, 920, "groupshape.scriptLang");
        addProp(m, 923, "groupshape.borderTopColor");
        addProp(m, 924, "groupshape.borderLeftColor");
        addProp(m, 925, "groupshape.borderBottomColor");
        addProp(m, 926, "groupshape.borderRightColor");
        addProp(m, 927, "groupshape.tableProperties");
        addProp(m, PDF417Common.MAX_CODEWORDS_IN_BARCODE, "groupshape.tableRowProperties");
        addProp(m, 933, "groupshape.wzWebBot");
        addProp(m, 937, "groupshape.metroBlob");
        addProp(m, 938, "groupshape.dhgt");
        addProp(m, 959, "groupshape.GroupShapeBooleanProperties");
        addProp(m, 953, "groupshape.editedwrap");
        addProp(m, 954, "groupshape.behinddocument");
        addProp(m, 955, "groupshape.ondblclicknotify");
        addProp(m, 956, "groupshape.isbutton");
        addProp(m, 957, "groupshape.1dadjustment");
        addProp(m, 958, "groupshape.hidden");
        addProp(m, 959, "groupshape.print", (byte) 1);
        return m;
    }

    private static void addProp(Map<Short, EscherPropertyMetaData> m, int s, String propName) {
        m.put(Short.valueOf((short) s), new EscherPropertyMetaData(propName));
    }

    private static void addProp(Map<Short, EscherPropertyMetaData> m, int s, String propName, byte type) {
        m.put(Short.valueOf((short) s), new EscherPropertyMetaData(propName, type));
    }

    public static String getPropertyName(short propertyId) {
        EscherPropertyMetaData o = (EscherPropertyMetaData) properties.get(Short.valueOf(propertyId));
        return o == null ? "unknown" : o.getDescription();
    }

    public static byte getPropertyType(short propertyId) {
        EscherPropertyMetaData escherPropertyMetaData = (EscherPropertyMetaData) properties.get(Short.valueOf(propertyId));
        return escherPropertyMetaData == null ? (byte) 0 : escherPropertyMetaData.getType();
    }
}
